job_id: tree-pruner-c26b8165-84c8-4af5-8ecd-11e24d949c73
email: adamulicny98@gmail.com
tree_base: birdtree
tree_set: EricsonStage2Full
sample_size: 100
names: [Aegithalos_caudatus, Certhia_familiaris, Carduelis_chloris, Coccothraustes_coccothraustes,
  Parus_caeruleus, Erithacus_rubecula, Ficedula_albicollis, Ficedula_hypoleuca, Fringilla_coelebs,
  Muscicapa_striata, Parus_major, Phylloscopus_collybita, Phylloscopus_sibilatrix,
  Parus_palustris, Sitta_europaea, Sturnus_vulgaris, Sylvia_atricapilla, Troglodytes_troglodytes,
  Turdus_merula, Turdus_philomelos]
sample_trees: [EricsonStage2Full_0004.tre, EricsonStage2Full_8173.tre, EricsonStage2Full_1166.tre,
  EricsonStage2Full_6352.tre, EricsonStage2Full_1639.tre, EricsonStage2Full_5109.tre,
  EricsonStage2Full_3475.tre, EricsonStage2Full_8464.tre, EricsonStage2Full_7318.tre,
  EricsonStage2Full_9725.tre, EricsonStage2Full_6719.tre, EricsonStage2Full_0451.tre,
  EricsonStage2Full_0610.tre, EricsonStage2Full_3428.tre, EricsonStage2Full_4487.tre,
  EricsonStage2Full_2071.tre, EricsonStage2Full_3240.tre, EricsonStage2Full_9695.tre,
  EricsonStage2Full_6815.tre, EricsonStage2Full_9589.tre, EricsonStage2Full_5907.tre,
  EricsonStage2Full_4381.tre, EricsonStage2Full_4690.tre, EricsonStage2Full_8304.tre,
  EricsonStage2Full_5099.tre, EricsonStage2Full_6427.tre, EricsonStage2Full_8070.tre,
  EricsonStage2Full_6826.tre, EricsonStage2Full_4127.tre, EricsonStage2Full_0087.tre,
  EricsonStage2Full_0308.tre, EricsonStage2Full_7451.tre, EricsonStage2Full_6711.tre,
  EricsonStage2Full_9206.tre, EricsonStage2Full_7860.tre, EricsonStage2Full_4177.tre,
  EricsonStage2Full_2090.tre, EricsonStage2Full_9037.tre, EricsonStage2Full_2120.tre,
  EricsonStage2Full_6571.tre, EricsonStage2Full_4753.tre, EricsonStage2Full_2994.tre,
  EricsonStage2Full_3874.tre, EricsonStage2Full_1138.tre, EricsonStage2Full_2794.tre,
  EricsonStage2Full_6373.tre, EricsonStage2Full_4467.tre, EricsonStage2Full_1380.tre,
  EricsonStage2Full_6903.tre, EricsonStage2Full_4055.tre, EricsonStage2Full_6533.tre,
  EricsonStage2Full_0290.tre, EricsonStage2Full_1714.tre, EricsonStage2Full_7525.tre,
  EricsonStage2Full_5752.tre, EricsonStage2Full_8307.tre, EricsonStage2Full_9648.tre,
  EricsonStage2Full_5494.tre, EricsonStage2Full_2750.tre, EricsonStage2Full_0472.tre,
  EricsonStage2Full_9662.tre, EricsonStage2Full_4325.tre, EricsonStage2Full_1816.tre,
  EricsonStage2Full_9472.tre, EricsonStage2Full_6598.tre, EricsonStage2Full_3831.tre,
  EricsonStage2Full_7411.tre, EricsonStage2Full_8104.tre, EricsonStage2Full_3130.tre,
  EricsonStage2Full_2030.tre, EricsonStage2Full_8719.tre, EricsonStage2Full_4134.tre,
  EricsonStage2Full_4305.tre, EricsonStage2Full_9586.tre, EricsonStage2Full_5691.tre,
  EricsonStage2Full_6907.tre, EricsonStage2Full_8961.tre, EricsonStage2Full_1636.tre,
  EricsonStage2Full_8696.tre, EricsonStage2Full_6570.tre, EricsonStage2Full_4478.tre,
  EricsonStage2Full_6285.tre, EricsonStage2Full_6800.tre, EricsonStage2Full_7198.tre,
  EricsonStage2Full_0899.tre, EricsonStage2Full_7485.tre, EricsonStage2Full_2838.tre,
  EricsonStage2Full_4086.tre, EricsonStage2Full_2520.tre, EricsonStage2Full_4782.tre,
  EricsonStage2Full_7426.tre, EricsonStage2Full_5281.tre, EricsonStage2Full_7501.tre,
  EricsonStage2Full_7443.tre, EricsonStage2Full_8009.tre, EricsonStage2Full_9862.tre,
  EricsonStage2Full_0102.tre, EricsonStage2Full_7177.tre, EricsonStage2Full_9064.tre,
  EricsonStage2Full_6710.tre]
status: CREATED
created_at: "2024-11-11T10:00:44Z"
completed_at: ""
bad_names: {}
