job_id: tree-pruner-8f88334b-2c2e-4a95-850c-226ea2fea2a6
email: adamulicny98@gmail.com
tree_base: birdtree
tree_set: EricsonStage2Full
sample_size: 100
names: [Abroscopus_superciliaris, Acanthagenys_rufogularis, Acanthiza_apicalis, Acanthiza_chrysorrhoa,
  Acanthiza_ewingii, Acanthiza_inornata, Acanthiza_lineata, Acanthiza_nana, Acanthiza_pusilla,
  Acanthiza_reguloides, Acanthiza_robustirostris, Acanthiza_uropygialis, Acanthorhynchus_superciliosus,
  Acanthorhynchus_tenuirostris, Acridotheres_fuscus, Acrocephalus_dumetorum, Actinodura_morrisoniana,
  Aegithalos_caudatus, Aegithalos_concinnus, Aegithina_tiphia, Aethopyga_christinae,
  Aethopyga_nipalensis, Ailuroedus_melanotis, Alcippe_manipurensis, Alcippe_morrisonia,
  Alcippe_poioicephala, Anthochaera_carunculata, Anthochaera_chrysoptera, Aphelocephala_leucopsis,
  Aplonis_metallica, Arses_kaupi, Artamus_cyanopterus, Artamus_superciliosus, Baeolophus_inornatus,
  Baeolophus_wollweberi, Carduelis_chloris, Carpodacus_vinaceus, Catharus_fuscescens,
  Catharus_guttatus, Catharus_ustulatus, Certhia_familiaris, Cettia_acanthizoides,
  Chloropsis_cochinchinensis, Chthonicola_sagittatus, Cissa_chinensis, Climacteris_affinis,
  Climacteris_erythrops, Climacteris_picumnus, Climacteris_rufus, Coccothraustes_coccothraustes,
  Colluricincla_boweri, Colluricincla_harmonica, Conopophila_albogularis, Coracina_lineata,
  Coracina_novaehollandiae, Corcorax_melanorhamphos, Cormobates_leucophaea, Corvus_macrorhynchos,
  Culicicapa_ceylonensis, Daphoenositta_chrysoptera, Dendrocitta_formosae, Dendroica_caerulescens,
  Dendroica_fusca, Dendroica_virens, Dicaeum_concolor, Dicaeum_erythrorhynchos, Dicaeum_hirundinaceum,
  Dicrurus_bracteatus, Dicrurus_caerulescens, Dicrurus_leucophaeus, Dicrurus_macrocercus,
  Dumetia_hyperythra, Empidonax_minimus, Empidonax_oberholseri, Entomyzon_cyanotis,
  Eopsaltria_australis, Eopsaltria_griseogularis, Eopsaltria_pulverulenta, Epthianura_tricolor,
  Erithacus_rubecula, Eumyias_albicaudatus, Falcunculus_frontatus, Ficedula_albicollis,
  Ficedula_nigrorufa, Fringilla_coelebs, Garrulax_leucolophus, Garrulax_morrisonianus,
  Garrulus_glandarius, Gerygone_chloronota, Gerygone_fusca, Gerygone_levigaster, Gerygone_magnirostris,
  Gerygone_mouki, Gerygone_olivacea, Gerygone_palpebrosa, Gymnorhina_tibicen, Hemipus_picatus,
  Heteromyias_albispecularis, Heterophasia_capistrata, Hirundo_daurica, Hylocichla_mustelina,
  Hypsipetes_leucocephalus, Icterus_bullockii, Icterus_parisorum, Iole_indica, Junco_hyemalis,
  Lalage_leucomela, Lanius_schach, Lanius_tephronotus, Leiothrix_lutea, Lichenostomus_chrysops,
  Lichenostomus_frenatus, Lichenostomus_fuscus, Lichenostomus_leucotis, Lichenostomus_melanops,
  Lichenostomus_ornatus, Lichenostomus_penicillatus, Lichenostomus_unicolor, Lichenostomus_virescens,
  Lichmera_indistincta, Liocichla_steerii, Macronous_gularis, Malacocincla_abbotti,
  Malurus_cyaneus, Malurus_pulcherrimus, Malurus_splendens, Manorina_melanocephala,
  Megarynchus_pitangua, Melanodryas_cucullata, Melanodryas_vittata, Meliphaga_gracilis,
  Meliphaga_lewinii, Melithreptus_albogularis, Melithreptus_brevirostris, Melithreptus_lunatus,
  Melithreptus_validirostris, Menura_novaehollandiae, Microeca_fascinans, Microeca_flavigaster,
  Minla_cyanouroptera, Minla_ignotincta, Monarcha_leucotis, Monarcha_melanopsis, Monarcha_trivirgatus,
  Muscicapa_ferruginea, Muscicapa_striata, Myiagra_alecto, Myiagra_cyanoleuca, Myiagra_inquieta,
  Myiagra_rubecula, Myiagra_ruficollis, Myiarchus_cinerascens, Myiomela_major, Myophonus_caeruleus,
  Myzomela_erythrocephala, Myzomela_obscura, Myzomela_sanguinolenta, Nectarinia_asiatica,
  Nectarinia_lotenia, Nectarinia_minima, Nectarinia_zeylonica, Neochmia_temporalis,
  Niltava_vivida, Oreoica_gutturalis, Oreoscopus_gutturalis, Oriolus_oriolus, Oriolus_xanthornus,
  Orthonyx_spaldingii, Orthotomus_sutorius, Pachycephala_melanura, Pachycephala_pectoralis,
  Pachycephala_rufiventris, Pachycephala_simplex, Paradoxornis_verreauxi, Pardalotus_punctatus,
  Pardalotus_striatus, Parus_ater, Parus_atricapillus, Parus_caeruleus, Parus_major,
  Parus_monticolus, Parus_palustris, Parus_spilonotus, Parus_xanthogenys, Pericrocotus_brevirostris,
  Pericrocotus_flammeus, Petroica_goodenovii, Petroica_multicolor, Petroica_phoenicea,
  Petroica_rosea, Pheucticus_ludovicianus, Philemon_buceroides, Philemon_citreogularis,
  Philemon_corniculatus, Phylidonyris_novaehollandiae, Phylidonyris_pyrrhopterus,
  Phylloscopus_affinis, Phylloscopus_collybita, Phylloscopus_inornatus, Phylloscopus_magnirostris,
  Phylloscopus_proregulus, Phylloscopus_reguloides, Phylloscopus_sibilatrix, Phylloscopus_trochiloides,
  Phylloscopus_xanthoschistos, Piranga_olivacea, Pitta_versicolor, Polioptila_caerulea,
  Pomatorhinus_horsfieldii, Pomatostomus_superciliosus, Psaltriparus_minimus, Psophodes_olivaceus,
  Ptiloris_victoriae, Pycnonotus_cafer, Pycnonotus_jocosus, Pycnonotus_luteolus, Pyrocephalus_rubinus,
  Pyrrhula_erythaca, Pyrrhula_nipalensis, Rhipidura_fuliginosa, Rhipidura_leucophrys,
  Rhipidura_phasiana, Rhipidura_rufifrons, Rhipidura_rufiventris, Seicercus_burkii,
  Seiurus_aurocapilla, Sericornis_citreogularis, Sericornis_frontalis, Sericornis_magnirostra,
  Setophaga_ruticilla, Sialia_mexicana, Sialia_sialis, Sitta_carolinensis, Sitta_castanea,
  Sitta_europaea, Sitta_frontalis, Smicrornis_brevirostris, Sphecotheres_vieilloti,
  Stachyris_erythroptera, Stagonopleura_guttata, Strepera_graculina, Strepera_versicolor,
  Strophocincla_cachinnans, Sylvia_atricapilla, Taeniopygia_guttata, Tarsiger_indicus,
  Tarsiger_johnstoniae, Terpsiphone_paradisi, Thryomanes_bewickii, Tregellasia_capito,
  Troglodytes_troglodytes, Turdoides_affinis, Turdoides_striata, Turdus_merula, Turdus_philomelos,
  Tyrannus_vociferans, Vermivora_luciae, Vireo_gilvus, Vireo_olivaceus, Vireo_philadelphicus,
  Vireo_solitarius, Xanthotis_macleayanus, Yuhina_brunneiceps, Yuhina_flavicollis,
  Yuhina_occipitalis, Zoothera_lunulata, Zosterops_japonicus, Zosterops_lateralis,
  Zosterops_luteus, Zosterops_palpebrosus]
sample_trees: [EricsonStage2Full_5377.tre, EricsonStage2Full_3993.tre, EricsonStage2Full_7524.tre,
  EricsonStage2Full_9934.tre, EricsonStage2Full_3517.tre, EricsonStage2Full_0523.tre,
  EricsonStage2Full_0854.tre, EricsonStage2Full_5100.tre, EricsonStage2Full_4496.tre,
  EricsonStage2Full_4455.tre, EricsonStage2Full_8635.tre, EricsonStage2Full_4364.tre,
  EricsonStage2Full_6661.tre, EricsonStage2Full_5359.tre, EricsonStage2Full_7500.tre,
  EricsonStage2Full_4120.tre, EricsonStage2Full_7944.tre, EricsonStage2Full_7200.tre,
  EricsonStage2Full_3116.tre, EricsonStage2Full_4853.tre, EricsonStage2Full_7591.tre,
  EricsonStage2Full_0095.tre, EricsonStage2Full_5415.tre, EricsonStage2Full_6253.tre,
  EricsonStage2Full_5150.tre, EricsonStage2Full_4589.tre, EricsonStage2Full_3711.tre,
  EricsonStage2Full_9538.tre, EricsonStage2Full_8031.tre, EricsonStage2Full_7991.tre,
  EricsonStage2Full_5668.tre, EricsonStage2Full_9878.tre, EricsonStage2Full_3537.tre,
  EricsonStage2Full_4046.tre, EricsonStage2Full_7093.tre, EricsonStage2Full_3925.tre,
  EricsonStage2Full_5807.tre, EricsonStage2Full_8642.tre, EricsonStage2Full_9230.tre,
  EricsonStage2Full_3003.tre, EricsonStage2Full_2884.tre, EricsonStage2Full_8476.tre,
  EricsonStage2Full_9641.tre, EricsonStage2Full_5027.tre, EricsonStage2Full_8985.tre,
  EricsonStage2Full_7257.tre, EricsonStage2Full_7451.tre, EricsonStage2Full_4944.tre,
  EricsonStage2Full_7820.tre, EricsonStage2Full_6734.tre, EricsonStage2Full_5363.tre,
  EricsonStage2Full_3345.tre, EricsonStage2Full_4797.tre, EricsonStage2Full_9352.tre,
  EricsonStage2Full_1835.tre, EricsonStage2Full_8115.tre, EricsonStage2Full_7896.tre,
  EricsonStage2Full_6688.tre, EricsonStage2Full_2267.tre, EricsonStage2Full_7637.tre,
  EricsonStage2Full_8222.tre, EricsonStage2Full_4628.tre, EricsonStage2Full_3118.tre,
  EricsonStage2Full_3694.tre, EricsonStage2Full_3542.tre, EricsonStage2Full_5777.tre,
  EricsonStage2Full_2521.tre, EricsonStage2Full_9303.tre, EricsonStage2Full_0542.tre,
  EricsonStage2Full_0119.tre, EricsonStage2Full_7261.tre, EricsonStage2Full_4244.tre,
  EricsonStage2Full_6087.tre, EricsonStage2Full_5856.tre, EricsonStage2Full_0410.tre,
  EricsonStage2Full_4504.tre, EricsonStage2Full_3275.tre, EricsonStage2Full_6940.tre,
  EricsonStage2Full_0738.tre, EricsonStage2Full_2141.tre, EricsonStage2Full_6976.tre,
  EricsonStage2Full_9651.tre, EricsonStage2Full_5471.tre, EricsonStage2Full_3736.tre,
  EricsonStage2Full_8041.tre, EricsonStage2Full_4172.tre, EricsonStage2Full_3375.tre,
  EricsonStage2Full_5725.tre, EricsonStage2Full_8395.tre, EricsonStage2Full_5647.tre,
  EricsonStage2Full_2440.tre, EricsonStage2Full_7052.tre, EricsonStage2Full_0823.tre,
  EricsonStage2Full_2125.tre, EricsonStage2Full_6061.tre, EricsonStage2Full_9985.tre,
  EricsonStage2Full_6618.tre, EricsonStage2Full_1310.tre, EricsonStage2Full_5445.tre,
  EricsonStage2Full_3274.tre]
status: COMPLETED
created_at: "2025-02-17T07:29:54Z"
completed_at: "2025-02-17T07:30:31Z"
bad_names: {EricsonStage2Full_0095.tre: [], EricsonStage2Full_0119.tre: [], EricsonStage2Full_0410.tre: [],
  EricsonStage2Full_0523.tre: [], EricsonStage2Full_0542.tre: [], EricsonStage2Full_0738.tre: [],
  EricsonStage2Full_0823.tre: [], EricsonStage2Full_0854.tre: [], EricsonStage2Full_1310.tre: [],
  EricsonStage2Full_1835.tre: [], EricsonStage2Full_2125.tre: [], EricsonStage2Full_2141.tre: [],
  EricsonStage2Full_2267.tre: [], EricsonStage2Full_2440.tre: [], EricsonStage2Full_2521.tre: [],
  EricsonStage2Full_2884.tre: [], EricsonStage2Full_3003.tre: [], EricsonStage2Full_3116.tre: [],
  EricsonStage2Full_3118.tre: [], EricsonStage2Full_3274.tre: [], EricsonStage2Full_3275.tre: [],
  EricsonStage2Full_3345.tre: [], EricsonStage2Full_3375.tre: [], EricsonStage2Full_3517.tre: [],
  EricsonStage2Full_3537.tre: [], EricsonStage2Full_3542.tre: [], EricsonStage2Full_3694.tre: [],
  EricsonStage2Full_3711.tre: [], EricsonStage2Full_3736.tre: [], EricsonStage2Full_3925.tre: [],
  EricsonStage2Full_3993.tre: [], EricsonStage2Full_4046.tre: [], EricsonStage2Full_4120.tre: [],
  EricsonStage2Full_4172.tre: [], EricsonStage2Full_4244.tre: [], EricsonStage2Full_4364.tre: [],
  EricsonStage2Full_4455.tre: [], EricsonStage2Full_4496.tre: [], EricsonStage2Full_4504.tre: [],
  EricsonStage2Full_4589.tre: [], EricsonStage2Full_4628.tre: [], EricsonStage2Full_4797.tre: [],
  EricsonStage2Full_4853.tre: [], EricsonStage2Full_4944.tre: [], EricsonStage2Full_5027.tre: [],
  EricsonStage2Full_5100.tre: [], EricsonStage2Full_5150.tre: [], EricsonStage2Full_5359.tre: [],
  EricsonStage2Full_5363.tre: [], EricsonStage2Full_5377.tre: [], EricsonStage2Full_5415.tre: [],
  EricsonStage2Full_5445.tre: [], EricsonStage2Full_5471.tre: [], EricsonStage2Full_5647.tre: [],
  EricsonStage2Full_5668.tre: [], EricsonStage2Full_5725.tre: [], EricsonStage2Full_5777.tre: [],
  EricsonStage2Full_5807.tre: [], EricsonStage2Full_5856.tre: [], EricsonStage2Full_6061.tre: [],
  EricsonStage2Full_6087.tre: [], EricsonStage2Full_6253.tre: [], EricsonStage2Full_6618.tre: [],
  EricsonStage2Full_6661.tre: [], EricsonStage2Full_6688.tre: [], EricsonStage2Full_6734.tre: [],
  EricsonStage2Full_6940.tre: [], EricsonStage2Full_6976.tre: [], EricsonStage2Full_7052.tre: [],
  EricsonStage2Full_7093.tre: [], EricsonStage2Full_7200.tre: [], EricsonStage2Full_7257.tre: [],
  EricsonStage2Full_7261.tre: [], EricsonStage2Full_7451.tre: [], EricsonStage2Full_7500.tre: [],
  EricsonStage2Full_7524.tre: [], EricsonStage2Full_7591.tre: [], EricsonStage2Full_7637.tre: [],
  EricsonStage2Full_7820.tre: [], EricsonStage2Full_7896.tre: [], EricsonStage2Full_7944.tre: [],
  EricsonStage2Full_7991.tre: [], EricsonStage2Full_8031.tre: [], EricsonStage2Full_8041.tre: [],
  EricsonStage2Full_8115.tre: [], EricsonStage2Full_8222.tre: [], EricsonStage2Full_8395.tre: [],
  EricsonStage2Full_8476.tre: [], EricsonStage2Full_8635.tre: [], EricsonStage2Full_8642.tre: [],
  EricsonStage2Full_8985.tre: [], EricsonStage2Full_9230.tre: [], EricsonStage2Full_9303.tre: [],
  EricsonStage2Full_9352.tre: [], EricsonStage2Full_9538.tre: [], EricsonStage2Full_9641.tre: [],
  EricsonStage2Full_9651.tre: [], EricsonStage2Full_9878.tre: [], EricsonStage2Full_9934.tre: [],
  EricsonStage2Full_9985.tre: []}
