job_id: tree-pruner-113588d6-96d9-4ade-8111-84775c129b3e
email: adamulicny98@gmail.com
tree_base: birdtree
tree_set: EricsonStage2Full
sample_size: 100
names: [Carduelis_chloris, Parus_palustris, Parus_caeruleus, Parus_major, Sylvia_atricapilla,
  Phylloscopus_sibilatrix, Phylloscopus_collybita, Certhia_familiaris, Troglodytes_troglodytes,
  Sitta_europaea, Turdus_philomelos, Turdus_merula, Erithacus_rubecula, Ficedula_hypoleuca,
  Ficedula_albicollis, Muscicapa_striata, Coccothraustes_coccothraustes, Fringilla_coelebs]
sample_trees: [EricsonStage2Full_2658.tre, EricsonStage2Full_8753.tre, EricsonStage2Full_6994.tre,
  EricsonStage2Full_1314.tre, EricsonStage2Full_9295.tre, EricsonStage2Full_5550.tre,
  EricsonStage2Full_2890.tre, EricsonStage2Full_4867.tre, EricsonStage2Full_1358.tre,
  EricsonStage2Full_1024.tre, EricsonStage2Full_9174.tre, EricsonStage2Full_1893.tre,
  EricsonStage2Full_2179.tre, EricsonStage2Full_1229.tre, EricsonStage2Full_0661.tre,
  EricsonStage2Full_6409.tre, EricsonStage2Full_2062.tre, EricsonStage2Full_7878.tre,
  EricsonStage2Full_8597.tre, EricsonStage2Full_3138.tre, EricsonStage2Full_1457.tre,
  EricsonStage2Full_0553.tre, EricsonStage2Full_7936.tre, EricsonStage2Full_1086.tre,
  EricsonStage2Full_7818.tre, EricsonStage2Full_4496.tre, EricsonStage2Full_9758.tre,
  EricsonStage2Full_8325.tre, EricsonStage2Full_5492.tre, EricsonStage2Full_9505.tre,
  EricsonStage2Full_2135.tre, EricsonStage2Full_1098.tre, EricsonStage2Full_6905.tre,
  EricsonStage2Full_7885.tre, EricsonStage2Full_6923.tre, EricsonStage2Full_1753.tre,
  EricsonStage2Full_8594.tre, EricsonStage2Full_6993.tre, EricsonStage2Full_3112.tre,
  EricsonStage2Full_8105.tre, EricsonStage2Full_3695.tre, EricsonStage2Full_5452.tre,
  EricsonStage2Full_0267.tre, EricsonStage2Full_5516.tre, EricsonStage2Full_2846.tre,
  EricsonStage2Full_2223.tre, EricsonStage2Full_9577.tre, EricsonStage2Full_7334.tre,
  EricsonStage2Full_4989.tre, EricsonStage2Full_2020.tre, EricsonStage2Full_1183.tre,
  EricsonStage2Full_5959.tre, EricsonStage2Full_2843.tre, EricsonStage2Full_4427.tre,
  EricsonStage2Full_4580.tre, EricsonStage2Full_6336.tre, EricsonStage2Full_4650.tre,
  EricsonStage2Full_6257.tre, EricsonStage2Full_2333.tre, EricsonStage2Full_5067.tre,
  EricsonStage2Full_4262.tre, EricsonStage2Full_5332.tre, EricsonStage2Full_1504.tre,
  EricsonStage2Full_6881.tre, EricsonStage2Full_3047.tre, EricsonStage2Full_9142.tre,
  EricsonStage2Full_7941.tre, EricsonStage2Full_8864.tre, EricsonStage2Full_7184.tre,
  EricsonStage2Full_1895.tre, EricsonStage2Full_9451.tre, EricsonStage2Full_8138.tre,
  EricsonStage2Full_9915.tre, EricsonStage2Full_5793.tre, EricsonStage2Full_4636.tre,
  EricsonStage2Full_6323.tre, EricsonStage2Full_6871.tre, EricsonStage2Full_9944.tre,
  EricsonStage2Full_3799.tre, EricsonStage2Full_7226.tre, EricsonStage2Full_7199.tre,
  EricsonStage2Full_7774.tre, EricsonStage2Full_4556.tre, EricsonStage2Full_7581.tre,
  EricsonStage2Full_8088.tre, EricsonStage2Full_4248.tre, EricsonStage2Full_1932.tre,
  EricsonStage2Full_2468.tre, EricsonStage2Full_2055.tre, EricsonStage2Full_7545.tre,
  EricsonStage2Full_9188.tre, EricsonStage2Full_8252.tre, EricsonStage2Full_8425.tre,
  EricsonStage2Full_2595.tre, EricsonStage2Full_1040.tre, EricsonStage2Full_0361.tre,
  EricsonStage2Full_7333.tre, EricsonStage2Full_0271.tre, EricsonStage2Full_2664.tre,
  EricsonStage2Full_2158.tre]
status: COMPLETED
created_at: "2023-11-27T16:36:06Z"
completed_at: "2023-11-27T16:36:47Z"
bad_names: {EricsonStage2Full_0267.tre: [], EricsonStage2Full_0271.tre: [], EricsonStage2Full_0361.tre: [],
  EricsonStage2Full_0553.tre: [], EricsonStage2Full_0661.tre: [], EricsonStage2Full_1024.tre: [],
  EricsonStage2Full_1040.tre: [], EricsonStage2Full_1086.tre: [], EricsonStage2Full_1098.tre: [],
  EricsonStage2Full_1183.tre: [], EricsonStage2Full_1229.tre: [], EricsonStage2Full_1314.tre: [],
  EricsonStage2Full_1358.tre: [], EricsonStage2Full_1457.tre: [], EricsonStage2Full_1504.tre: [],
  EricsonStage2Full_1753.tre: [], EricsonStage2Full_1893.tre: [], EricsonStage2Full_1895.tre: [],
  EricsonStage2Full_1932.tre: [], EricsonStage2Full_2020.tre: [], EricsonStage2Full_2055.tre: [],
  EricsonStage2Full_2062.tre: [], EricsonStage2Full_2135.tre: [], EricsonStage2Full_2158.tre: [],
  EricsonStage2Full_2179.tre: [], EricsonStage2Full_2223.tre: [], EricsonStage2Full_2333.tre: [],
  EricsonStage2Full_2468.tre: [], EricsonStage2Full_2595.tre: [], EricsonStage2Full_2658.tre: [],
  EricsonStage2Full_2664.tre: [], EricsonStage2Full_2843.tre: [], EricsonStage2Full_2846.tre: [],
  EricsonStage2Full_2890.tre: [], EricsonStage2Full_3047.tre: [], EricsonStage2Full_3112.tre: [],
  EricsonStage2Full_3138.tre: [], EricsonStage2Full_3695.tre: [], EricsonStage2Full_3799.tre: [],
  EricsonStage2Full_4248.tre: [], EricsonStage2Full_4262.tre: [], EricsonStage2Full_4427.tre: [],
  EricsonStage2Full_4496.tre: [], EricsonStage2Full_4556.tre: [], EricsonStage2Full_4580.tre: [],
  EricsonStage2Full_4636.tre: [], EricsonStage2Full_4650.tre: [], EricsonStage2Full_4867.tre: [],
  EricsonStage2Full_4989.tre: [], EricsonStage2Full_5067.tre: [], EricsonStage2Full_5332.tre: [],
  EricsonStage2Full_5452.tre: [], EricsonStage2Full_5492.tre: [], EricsonStage2Full_5516.tre: [],
  EricsonStage2Full_5550.tre: [], EricsonStage2Full_5793.tre: [], EricsonStage2Full_5959.tre: [],
  EricsonStage2Full_6257.tre: [], EricsonStage2Full_6323.tre: [], EricsonStage2Full_6336.tre: [],
  EricsonStage2Full_6409.tre: [], EricsonStage2Full_6871.tre: [], EricsonStage2Full_6881.tre: [],
  EricsonStage2Full_6905.tre: [], EricsonStage2Full_6923.tre: [], EricsonStage2Full_6993.tre: [],
  EricsonStage2Full_6994.tre: [], EricsonStage2Full_7184.tre: [], EricsonStage2Full_7199.tre: [],
  EricsonStage2Full_7226.tre: [], EricsonStage2Full_7333.tre: [], EricsonStage2Full_7334.tre: [],
  EricsonStage2Full_7545.tre: [], EricsonStage2Full_7581.tre: [], EricsonStage2Full_7774.tre: [],
  EricsonStage2Full_7818.tre: [], EricsonStage2Full_7878.tre: [], EricsonStage2Full_7885.tre: [],
  EricsonStage2Full_7936.tre: [], EricsonStage2Full_7941.tre: [], EricsonStage2Full_8088.tre: [],
  EricsonStage2Full_8105.tre: [], EricsonStage2Full_8138.tre: [], EricsonStage2Full_8252.tre: [],
  EricsonStage2Full_8325.tre: [], EricsonStage2Full_8425.tre: [], EricsonStage2Full_8594.tre: [],
  EricsonStage2Full_8597.tre: [], EricsonStage2Full_8753.tre: [], EricsonStage2Full_8864.tre: [],
  EricsonStage2Full_9142.tre: [], EricsonStage2Full_9174.tre: [], EricsonStage2Full_9188.tre: [],
  EricsonStage2Full_9295.tre: [], EricsonStage2Full_9451.tre: [], EricsonStage2Full_9505.tre: [],
  EricsonStage2Full_9577.tre: [], EricsonStage2Full_9758.tre: [], EricsonStage2Full_9915.tre: [],
  EricsonStage2Full_9944.tre: []}
