job_id: tree-pruner-8db6dd25-aef8-41f5-9f56-e8187c5362fe
email: adamulicny98@gmail.com
tree_base: birdtree
tree_set: EricsonStage2Full
sample_size: 100
names: [Ailuroedus_melanotis, Aplonis_metallica, Arses_kaupi, Cacatua_alba, Monarcha_leucotis,
  Coracina_lineata, Dicaeum_hirundinaceum, Eudynamys_orientalis, Gerygone_palpebrosa,
  Lalage_leucomela, Ptiloris_victoriae, Megarynchus_pitangua, Meliphaga_gracilis,
  Myzomela_obscura, Orthonyx_spaldingii, Pachycephala_simplex, Pitta_versicolor, Rhipidura_fuliginosa,
  Rhipidura_rufifrons, Sericornis_magnirostra, Sphecotheres_vieilloti, Monarcha_trivirgatus,
  Tregellasia_capito, Xanthotis_macleayanus, Zosterops_lateralis, Ptilinopus_magnificus,
  Macropygia_amboinensis, Platycercus_elegans, Meliphaga_lewinii, Lichenostomus_frenatus,
  Acanthorhynchus_tenuirostris, Neochmia_temporalis, Pachycephala_pectoralis, Colluricincla_boweri,
  Gerygone_mouki, Climacteris_picumnus, Alectura_lathami, Heteromyias_albispecularis,
  Psophodes_olivaceus, Oreoscopus_gutturalis, Sericornis_citreogularis, Junco_hyemalis,
  Catharus_guttatus, Catharus_ustulatus, Troglodytes_troglodytes, Seiurus_aurocapilla,
  Catharus_fuscescens, Hylocichla_mustelina, Picoides_villosus, Sphyrapicus_varius,
  Picoides_pubescens, Sitta_carolinensis, Vireo_solitarius, Dendroica_fusca, Parus_atricapillus,
  Dendroica_virens, Vireo_olivaceus, Vireo_philadelphicus, Pheucticus_ludovicianus,
  Piranga_olivacea, Empidonax_minimus, Setophaga_ruticilla, Dendroica_caerulescens,
  Acanthiza_uropygialis, Stagonopleura_guttata, Melanodryas_cucullata, Microeca_fascinans,
  Petroica_goodenovii, Petroica_multicolor, Aphelocephala_leucopsis, Malurus_cyaneus,
  Pomatostomus_superciliosus, Rhipidura_leucophrys, Corcorax_melanorhamphos, Acanthiza_chrysorrhoa,
  Gerygone_chloronota, Gerygone_magnirostris, Conopophila_albogularis, Lichenostomus_unicolor,
  Zosterops_luteus, Myiagra_ruficollis, Microeca_flavigaster, Chrysococcyx_minutillus,
  Pachycephala_melanura, Eopsaltria_pulverulenta, Rhipidura_rufiventris, Myiagra_alecto,
  Merops_ornatus, Lichmera_indistincta, Philemon_buceroides, Myzomela_erythrocephala,
  Melanerpes_formicivorus, Thryomanes_bewickii, Icterus_parisorum, Baeolophus_wollweberi,
  Psaltriparus_minimus, Vermivora_luciae, Myiarchus_cinerascens, Sialia_sialis, Empidonax_oberholseri,
  Pyrocephalus_rubinus, Tyrannus_vociferans, Melanerpes_uropygialis, Picoides_scalaris,
  Picoides_arizonae, Picoides_nuttallii, Icterus_bullockii, Baeolophus_inornatus,
  Polioptila_caerulea, Vireo_gilvus, Sialia_mexicana, Gerygone_levigaster, Rhipidura_phasiana,
  Myiagra_rubecula, Dicrurus_leucophaeus, Terpsiphone_paradisi, Hypsipetes_leucocephalus,
  Dicrurus_macrocercus, Oriolus_xanthornus, Psittacula_roseata, Phaenicophaeus_viridirostris,
  Chloropsis_cochinchinensis, Phylloscopus_reguloides, Megalaima_zeylanica, Merops_leschenaulti,
  Upupa_epops, Aegithina_tiphia, Orthotomus_sutorius, Merops_orientalis, Phylloscopus_trochiloides,
  Gallus_sonneratii, Pavo_cristatus, Turdoides_striata, Acridotheres_fuscus, Phylloscopus_magnirostris,
  Nectarinia_lotenia, Psittacula_columboides, Dicaeum_erythrorhynchos, Dicaeum_concolor,
  Nectarinia_asiatica, Nectarinia_zeylonica, Hirundo_daurica, Pycnonotus_cafer, Pycnonotus_jocosus,
  Picus_xanthopygaeus, Dumetia_hyperythra, Loriculus_vernalis, Dicrurus_caerulescens,
  Pycnonotus_luteolus, Turdoides_affinis, Aegithalos_caudatus, Carduelis_citrinella,
  Carduelis_spinus, Certhia_brachydactyla, Dendrocopos_major, Erithacus_rubecula,
  Ficedula_hypoleuca, Fringilla_coelebs, Loxia_curvirostra, Parus_ater, Parus_caeruleus,
  Parus_cristatus, Parus_major, Phylloscopus_bonelli, Phylloscopus_collybita, Prunella_modularis,
  Regulus_ignicapilla, Regulus_regulus, Sitta_europaea, Sylvia_atricapilla, Sylvia_borin,
  Turdus_merula, Turdus_philomelos, Turdus_viscivorus, Syrmaticus_mikado, Columba_pulchricollis,
  Cuculus_saturatus, Glaucidium_brodiei, Dendrocopos_leucotos, Picus_canus, Nucifraga_caryocatactes,
  Corvus_macrorhynchos, Garrulus_glandarius, Parus_monticolus, Aegithalos_concinnus,
  Cettia_acanthizoides, Bradypterus_alishanensis, Abroscopus_albogularis, Pnoepyga_albiventer,
  Stachyris_ruficeps, Garrulax_morrisonianus, Liocichla_steerii, Actinodura_morrisoniana,
  Alcippe_manipurensis, Alcippe_morrisonia, Heterophasia_auricularis, Yuhina_brunneiceps,
  Paradoxornis_verreauxi, Regulus_goodfellowi, Myophonus_insularis, Brachypteryx_montana,
  Tarsiger_indicus, Tarsiger_johnstoniae, Muscicapa_ferruginea, Ficedula_hyperythra,
  Niltava_vivida, Carpodacus_vinaceus, Pyrrhula_nipalensis, Pyrrhula_erythaca, Myophonus_caeruleus,
  Minla_cyanouroptera, Sitta_castanea, Cissa_chinensis, Megalaima_virens, Seicercus_burkii,
  Aethopyga_nipalensis, Culicicapa_ceylonensis, Lanius_tephronotus, Dendrocitta_formosae,
  Phylloscopus_xanthoschistos, Picus_chlorolophus, Minla_ignotincta, Leiothrix_lutea,
  Heterophasia_capistrata, Yuhina_occipitalis, Pericrocotus_brevirostris, Dicrurus_bracteatus,
  Stigmatopelia_chinensis, Sitta_frontalis, Yuhina_flavicollis, Garrulax_leucolophus,
  Abroscopus_superciliaris, Mniotilta_varia, Parus_carolinensis, Thryothorus_ludovicianus,
  Sayornis_phoebe, Baeolophus_bicolor, Dendroica_coronata, Cardinalis_cardinalis,
  Vermivora_celata, Dendroica_pinus, Melanerpes_carolinus, Regulus_calendula, Vireo_griseus,
  Dendroica_dominica, Zosterops_japonicus, Parus_spilonotus, Aethopyga_christinae,
  Phylloscopus_inornatus, Phylloscopus_proregulus, Erpornis_zantholeuca, Hypothymis_azurea,
  Aegithina_viridissima, Muscicapa_dauurica, Phylloscopus_borealis, Macronous_gularis,
  Stachyris_erythroptera, Malacocincla_abbotti, Prinia_rufescens, Hemipus_picatus,
  Ficedula_nigrorufa, Parus_xanthogenys, Acrocephalus_dumetorum, Alcippe_poioicephala,
  Nectarinia_minima, Dinopium_javanense, Strophocincla_cachinnans, Pomatorhinus_horsfieldii,
  Lanius_schach, Eumyias_albicaudatus, Columba_elphinstonii, Zosterops_palpebrosus,
  Pericrocotus_flammeus, Phylloscopus_affinis, Myiomela_major, Megalaima_viridis,
  Iole_indica, Acanthiza_lineata, Acanthiza_nana, Acanthiza_pusilla, Acanthiza_reguloides,
  Anthochaera_carunculata, Colluricincla_harmonica, Cormobates_leucophaea, Gymnorhina_tibicen,
  Daphoenositta_chrysoptera, Entomyzon_cyanotis, Eopsaltria_australis, Lichenostomus_fuscus,
  Lichenostomus_chrysops, Lichenostomus_leucotis, Lichenostomus_melanops, Lichenostomus_penicillatus,
  Manorina_melanocephala, Melithreptus_albogularis, Melithreptus_brevirostris, Melithreptus_lunatus,
  Myzomela_sanguinolenta, Pachycephala_rufiventris, Pardalotus_punctatus, Pardalotus_striatus,
  Philemon_citreogularis, Philemon_corniculatus, Phylidonyris_novaehollandiae, Sericornis_frontalis,
  Smicrornis_brevirostris, Strepera_graculina, Artamus_cyanopterus, Artamus_superciliosus,
  Coracina_novaehollandiae, Falcunculus_frontatus, Gerygone_olivacea, Myiagra_inquieta,
  Chthonicola_sagittatus, Climacteris_erythrops, Menura_novaehollandiae, Monarcha_melanopsis,
  Myiagra_cyanoleuca, Petroica_phoenicea, Petroica_rosea, Phylidonyris_pyrrhopterus,
  Zoothera_lunulata, Acanthorhynchus_superciliosus, Acanthiza_apicalis, Acanthiza_inornata,
  Anthochaera_chrysoptera, Climacteris_rufus, Eopsaltria_griseogularis, Gerygone_fusca,
  Lichenostomus_ornatus, Malurus_pulcherrimus, Malurus_splendens, Strepera_versicolor,
  Acanthagenys_rufogularis, Acanthiza_robustirostris, Climacteris_affinis, Epthianura_tricolor,
  Lichenostomus_virescens, Oreoica_gutturalis, Taeniopygia_guttata, Melanodryas_vittata,
  Melithreptus_validirostris, Acanthiza_ewingii, Certhia_familiaris, Carduelis_chloris,
  Coccothraustes_coccothraustes, Dendrocopos_medius, Dryocopus_martius, Ficedula_albicollis,
  Muscicapa_striata, Oriolus_oriolus, Phoenicurus_phoenicurus, Phylloscopus_sibilatrix,
  Parus_palustris, Sturnus_vulgaris]
sample_trees: [EricsonStage2Full_2650.tre, EricsonStage2Full_6595.tre, EricsonStage2Full_4623.tre,
  EricsonStage2Full_0304.tre, EricsonStage2Full_4771.tre, EricsonStage2Full_3496.tre,
  EricsonStage2Full_8821.tre, EricsonStage2Full_0223.tre, EricsonStage2Full_3272.tre,
  EricsonStage2Full_2813.tre, EricsonStage2Full_3077.tre, EricsonStage2Full_3775.tre,
  EricsonStage2Full_2211.tre, EricsonStage2Full_7474.tre, EricsonStage2Full_8535.tre,
  EricsonStage2Full_7531.tre, EricsonStage2Full_0479.tre, EricsonStage2Full_3316.tre,
  EricsonStage2Full_3234.tre, EricsonStage2Full_2656.tre, EricsonStage2Full_9022.tre,
  EricsonStage2Full_9270.tre, EricsonStage2Full_2505.tre, EricsonStage2Full_8254.tre,
  EricsonStage2Full_7928.tre, EricsonStage2Full_3726.tre, EricsonStage2Full_7118.tre,
  EricsonStage2Full_7548.tre, EricsonStage2Full_2808.tre, EricsonStage2Full_4422.tre,
  EricsonStage2Full_6888.tre, EricsonStage2Full_3222.tre, EricsonStage2Full_5966.tre,
  EricsonStage2Full_6268.tre, EricsonStage2Full_2827.tre, EricsonStage2Full_5585.tre,
  EricsonStage2Full_5249.tre, EricsonStage2Full_9195.tre, EricsonStage2Full_0787.tre,
  EricsonStage2Full_0615.tre, EricsonStage2Full_1975.tre, EricsonStage2Full_7245.tre,
  EricsonStage2Full_1537.tre, EricsonStage2Full_6942.tre, EricsonStage2Full_0212.tre,
  EricsonStage2Full_0215.tre, EricsonStage2Full_9315.tre, EricsonStage2Full_9258.tre,
  EricsonStage2Full_3458.tre, EricsonStage2Full_2613.tre, EricsonStage2Full_4002.tre,
  EricsonStage2Full_6110.tre, EricsonStage2Full_5772.tre, EricsonStage2Full_0303.tre,
  EricsonStage2Full_7419.tre, EricsonStage2Full_5460.tre, EricsonStage2Full_2205.tre,
  EricsonStage2Full_9591.tre, EricsonStage2Full_4607.tre, EricsonStage2Full_7513.tre,
  EricsonStage2Full_2246.tre, EricsonStage2Full_9522.tre, EricsonStage2Full_4546.tre,
  EricsonStage2Full_2832.tre, EricsonStage2Full_3148.tre, EricsonStage2Full_3438.tre,
  EricsonStage2Full_1312.tre, EricsonStage2Full_3704.tre, EricsonStage2Full_0798.tre,
  EricsonStage2Full_9290.tre, EricsonStage2Full_2663.tre, EricsonStage2Full_9778.tre,
  EricsonStage2Full_2131.tre, EricsonStage2Full_5304.tre, EricsonStage2Full_3375.tre,
  EricsonStage2Full_5475.tre, EricsonStage2Full_6161.tre, EricsonStage2Full_2574.tre,
  EricsonStage2Full_6474.tre, EricsonStage2Full_4330.tre, EricsonStage2Full_5802.tre,
  EricsonStage2Full_1978.tre, EricsonStage2Full_4295.tre, EricsonStage2Full_6532.tre,
  EricsonStage2Full_5010.tre, EricsonStage2Full_1998.tre, EricsonStage2Full_3176.tre,
  EricsonStage2Full_8681.tre, EricsonStage2Full_1119.tre, EricsonStage2Full_6357.tre,
  EricsonStage2Full_8488.tre, EricsonStage2Full_4492.tre, EricsonStage2Full_3873.tre,
  EricsonStage2Full_4861.tre, EricsonStage2Full_1503.tre, EricsonStage2Full_1952.tre,
  EricsonStage2Full_5843.tre, EricsonStage2Full_6680.tre, EricsonStage2Full_1980.tre,
  EricsonStage2Full_4954.tre]
status: CREATED
created_at: "2025-02-09T13:08:12Z"
completed_at: ""
bad_names: {}
